/*
** EPITECH PROJECT, 2023
** B-CPE-110-RUN-1-1-antman-pierre-alexandre.grosset
** File description:
** my_perror_header
*/

#ifndef MY_PERROR_HEADER_H_
    #define MY_PERROR_HEADER_H_

    #define ERR_VALUE 84

    #define ERR_ERR_CHCK "00 - FAILED TO START ANTMAN PROGRAMM\n"
    #define ERR_ARG_INVD "02 - ARGUMENT 2 MUST BE A FIGURE\n"
    #define ERR_ARG_TYPE "03 - ARGUMENT 2 MUST BE 1 | 2 | 3\n"
    #define ERR_NOT_FILE "04 - ARGUMENT IS NOT A FILE\n"
    #define ERR_ORD_FAIL "05 - INVALID FILE - COULD NOT READ\n"
    #define ERR_INV_STAT_CALL "06 - STAT FAILED TO RETURN VALID VALUE\n"
    #define ERR_INV_FILE_SIZE "07 - INVALID FILE SIZE - EMPTY FILE\n"
    #define ERR_INV_FILE "08 - INVALID FILE ERROR\n"
    #define ERR_GET_FILE_SIZE_FAIL "09 - FAILED TO GET VALID FILE SIZE\n"
    #define ERR_MALLOC_FAIL "10 - COULD NOT MALLOC - MALLOC FAIL\n"
    #define ERR_GET_CONTENT_FAIL "11 - FAILED TO GET FILE CONTENT\n"
    #define ERR_GET_OCCURENCES_LIST "12 - COULD NOT GET THE OCCURENCES LIST\n"
    #define ERR_LYR_FAILED_COMPRESSION "13 - FAILED TO COMPRESS LYR FILE\n"
    #define ERR_HTML_FAILED_COMPRESSION "14 - FAILED TO COMPRESS HTML FILE\n"
    #define ERR_PPM_FAILED_COMPRESSION "15 - FAILED TO COMPRESS PPM FILE\n"
    #define ERR_INV_GET_NMBR "16 - GET NBR RETURNED THE ERR VALUE -84\n"
    #define ERR_LYR_FAILED_DECOMPRESSION "17 - FAILED TO COMPRESS LYR FILE\n"
    #define ERR_HTML_FAILED_DECOMPRESSION "18 - FAILED TO COMPRESS HTML FILE\n"
    #define ERR_PPM_FAILED_DECOMPRESSION "19 - FAILED TO COMPRESS PPM FILE\n"

    #define ERR_ARG_NMBR "00 - INVALID ARG NUMBER\n"
    #define ERR_BOARD_LOAD "01 - COULD NOT LOAD HOST BOARD\n"
    #define ERR_OPEN_FILE "02 - COULD NOT OPEN THE FILE\n"
    #define ERR_INV_PID "03 - PLEASE GIVE VALID PARAMETER PID\n"
    #define ERR_PID_VALUE "04 - TRY GIVING A VALID PID\n"
    #define ERR_GEN_BOARD "05 - COULD NOT GENERATE VALID BOARD FROM FILE\n"
    #define ERR_FILE_CONTENT "06 - INVALID FILE CONTENT\n"
    #define ERR_INV_LINE "07 - INVALID DATA\n"
    #define ERR_FILL_IN "08 - FAILED TO PUT DATA INTO BOARD\n"
    #define ERR_BOAT_ERR "09 - OVERLAPPING BOATS\n"
#endif /* !MY_PERROR_HEADER_H_ */
